config/routes.rb
PaymoneyAdministration::Application.routes.draw do
  root :to => redirect("/users/sign_in")
  
  resources :statuses
  
  
  devise_for :users, :controllers => {:registrations => "devise/registrations", :sessions => "devise/sessions", :passwords => "devise/passwords"}
  
  devise_scope :user do
  	get 'dashboard' => 'devise/registrations#new', :as => :administrator_dashboard
  	get "user/edit_profile/:id" => "devise/registrations#edit", :as => :edit_user_profile
  	patch 'user/update_profile' => 'devise/registrations#update_profile', :as => :update_user_profile
  end
  
  get 'user/search' => 'users#search', :as => :search_user
  get 'user/enable_profile/:id' => 'users#enable_profile', :as => :enable_user_profile
  get 'user/disable_profile/:id' => 'users#disable_profile', :as => :disable_user_profile 
  
  get "liste-des-comptes-actives" => "accounts#index", as: :enabled_accounts_list
  get "liste-des-comptes-desactives" => "accounts#disabled_accounts", as: :disabled_accounts_list
  get "liste-des-depots" => "accounts#credits", as: :list_credits
  get "liste-des-retraits" => "accounts#debits", as: :list_debits
  get "activer-un-compte/:account_id" => "accounts#enable_account", as: :enable_account
  get "desactiver-un-compte/:account_id" => "accounts#disable_account", as: :disable_account
  post "rechercher-un-compte" => "accounts#search"
  get "rechercher-un-compte" => "accounts#search"
  
  get "auditeur-liste-des-profils" => "profiles#auditor_index", as: :auditor_index
  get "liste-des-utilisateurs-par-profil/:profile_id" => "profiles#users_per_profile", as: :users_per_profile
  get "profile/custom" => "profiles#custom_profiles", as: :custom_profiles_dashboard
  get "profiles" => "profiles#index", as: :profiles
  post "profile/create" => "profiles#create"
  get "profile/create" => "profiles#index"
  get "profile/edit/:id" => "profiles#edit", as: :edit_profile
  post "profile/update" => "profiles#update"
  get "profile/update" => "profiles#index"
  get "profiles/edit_rights" => "profiles#edit_rights", as: :edit_profiles_rights
  get "profile/right/enable_create_user/:id" => "profiles#enable_create_user_right", as: :enable_create_user_right
  get "profile/right/disable_create_user/:id" => "profiles#disable_create_user_right", as: :disable_create_user_right
  get "profile/right/enable_edit_user_data/:id" => "profiles#enable_edit_user_data_right", as: :enable_edit_user_data_right
  get "profile/right/disable_edit_user_data/:id" => "profiles#disable_edit_user_data_right", as: :disable_edit_user_data_right
  
  get "profile/right/enable_create_profile/:id" => "profiles#enable_create_profile_right", as: :enable_create_profile_right
  get "profile/right/disable_create_profile/:id" => "profiles#disable_create_profile_right", as: :disable_create_profile_right
  
  get "profile/right/enable_edit_profile/:id" => "profiles#enable_edit_profile_right", as: :enable_edit_profile_right
  get "profile/right/disable_edit_profile/:id" => "profiles#disable_edit_profile_right", as: :disable_edit_profile_right
  
  get "profile/right/enable_view_transactions/:id" => "profiles#enable_view_transactions_right", as: :enable_view_transactions_right
  get "profile/right/disable_view_transactions/:id" => "profiles#disable_view_transactions_right", as: :disable_view_transactions_right
  
  get "profile/right/enable_disable_account/:id" => "profiles#enable_disable_account_right", as: :enable_disable_account_right
  get "profile/right/disable_disable_account/:id" => "profiles#disable_disable_account_right", as: :disable_disable_account_right
  
  get "profile/right/enable_disable_profile/:id" => "profiles#enable_disable_profile_right", as: :enable_disable_profile_right
  get "profile/right/disable_disable_profile/:id" => "profiles#disable_disable_profile_right", as: :disable_disable_profile_right
  

  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :users

  attr_accessible :id, :name, :published, :shortcut, :disable_profile, :edit_profile, :create_profile, :disable_account, :view_transactions, :edit_wallet, :create_wallet, :edit_bank, :create_bank, :edit_inheritor, :create_inheritor, :edit_operation, :create_operation, :edit_service, :create_service, :edit_user_data, :create_user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  @@parameters = Parameter.first  
  @@url = "http://hub.com"
  
  before_filter :sign_out_disabled_users
  prepend_before_filter :authenticate_user!
  
  layout :layout_used
  
  def custom_profiles
  
  end
  
  def auditor_index
    @namecss = @shortcutcss = "row-form"
    @profiles = Profile.where("shortcut NOT IN ('ADMIN-P', 'ADMIN-R', 'ADMIN-A', 'GBUM')").page(params[:page]).per_page(17)
  end
  
  def users_per_profile
    @profile = Profile.find_by_id(params[:profile_id])
    if @profile.blank?
      redirect_to auditor_index_path, :notice => "Ce profil n'existe pas."
    else
      @users = User.where("profile_id = #{@profile.id}").page(params[:page]).per_page(17)
    end
  end
  
  def index
    @namecss = @shortcutcss = "row-form"
    @profiles = Profile.where("shortcut NOT IN ('ADMIN-P', 'ADMIN-R', 'ADMIN-A', 'GBUM')").order("name ASC").page(params[:page]).per_page(17)
  end
  
  def create
    @error_messages = []
    @success_messages = []
    @namecss = @shortcutcss = "row-form"
    @name = params[:name]
    @shortcut = params[:shortcut]
    @profiles = Profile.where("shortcut NOT IN ('ADMIN-P', 'ADMIN-R', 'ADMIN-A', 'GBUM')").page(params[:page]).per_page(17)

    if Profile.find(:all, :conditions => ["name ILIKE ? OR shortcut ILIKE ?", @name, @shortcut]).blank?
      @fields = [[@name, "le nom du profil", "@namecss"], [@shortcut, "l'abbréviation du profil", "@shortcutcss"]]
      
      @fields.each do |field|
        if field[0].blank?
          @error_messages << "Veuillez entrer #{field[1]}."
          my_container = field[2]
          instance_variable_set("#{my_container}", "row-form error")
          @error = true
        end
      end
      
      unless @error 
        Profile.create(name: @name, shortcut: @shortcut.upcase)
        params[:name] = params[:shortcut] = nil
        @success_messages << "Le profil #{@name} a été créé." 
      end
    else
      @error_messages << "Le nom du profil ainsi que son abbréviation doivent être uniques."
    end
    
    render :action => "index"
  end
  
  def edit
    @namecss = @shortcutcss = "row-form"
     @profiles = Profile.where("shortcut NOT IN ('ADMIN-P', 'ADMIN-R', 'ADMIN-A', 'GBUM')").page(params[:page]).per_page(17)
    @profile = Profile.find_by_id(params[:id])
  end
  
  def update
    @error_messages = []
    @success_messages = []
    @namecss = @shortcutcss = "row-form"
    @profile = Profile.find_by_id(params[:id])
    @name = params[:name]
    @shortcut = params[:shortcut]
    @profiles = Profile.where("shortcut NOT IN ('ADMIN-P', 'ADMIN-R', 'ADMIN-A', 'GBUM')").page(params[:page]).per_page(17)

    if Profile.find(:all, :conditions => ["(name ILIKE ? OR shortcut ILIKE ?) AND id != ?", @name, @shortcut, @profile.id]).blank?
      @fields = [[@name, "le nom du profil", "@namecss"], [@shortcut, "l'abbréviation du profil", "@shortcutcss"]]
      
      @fields.each do |field|
        if field[0].blank?
          @error_messages << "Veuillez entrer #{field[1]}."
          my_container = field[2]
          instance_variable_set("#{my_container}", "row-form error")
          @error = true
        end
      end
      
      unless @error 
        @profile.update_columns(name: @name, shortcut: @shortcut.upcase)
        @success_messages << "Le profil #{@name} a été mis à jour." 
      end
    else
      @error_messages << "Le nom du profil ainsi que son abbréviation doivent être uniques."
    end
    
    
    render :action => "edit" 
  end
  
  def edit_rights
    @profiles = Profile.where("shortcut NOT IN ('ADMIN-P', 'ADMIN-R', 'ADMIN-A', 'GBUM')").order("name ASC").page(params[:page]).per_page(17)
  end
  
  def enable_create_user_right
    create_user_right(true, params[:id], "a maintenant")
  end
  
  def disable_create_user_right
    create_user_right(false, params[:id], "n'a plus")
  end
  
  def create_user_right(status, id, message)
    @profile = Profile.find_by_id(id)
    @profile.update_attributes(create_user: status)
    
    redirect_to edit_profiles_rights_path, :notice => "Le profil #{@profile.name} #{message} le droit de créer des utilisateurs."
  end
  
  def enable_edit_user_data_right
    edit_user_data_right(true, params[:id], "a maintenant")
  end
  
  def disable_edit_user_data_right
    edit_user_data_right(false, params[:id], "n'a plus")
  end
  
  def edit_user_data_right(status, id, message)
    #@profiles = Profile.where("shortcut NOT IN ('ADMIN-P', 'ADMIN-R', 'ADMIN-A', 'GBUM')").page(params[:page]).per_page(17)
    @profile = Profile.find_by_id(id)
    @profile.update_attributes(edit_user_data: status)
    
    redirect_to edit_profiles_rights_path, :notice => "Le profil #{@profile.name} #{message} le droit de modifier les profils utilisateurs."
  end
  
  def enable_create_profile_right
    create_profile_right(true, params[:id], "a maintenant")
  end
  
  def disable_create_profile_right
    create_profile_right(false, params[:id], "n'a plus")
  end
  
  def create_profile_right(status, id, message)
    @profile = Profile.find_by_id(id)
    @profile.update_attributes(create_profile: status)
    
    redirect_to edit_profiles_rights_path, :notice => "Le profil #{@profile.name} #{message} le droit de modifier les profils utilisateurs."
  end
  
  def enable_edit_profile_right
    edit_profile_right(true, params[:id], "a maintenant")
  end
  
  def disable_edit_profile_right
    edit_profile_right(false, params[:id], "n'a plus")
  end
  
  def edit_profile_right(status, id, message)
    @profile = Profile.find_by_id(id)
    @profile.update_attributes(edit_profile: status)
    
    redirect_to edit_profiles_rights_path, :notice => "Le profil #{@profile.name} #{message} le droit de modifier les profils utilisateurs."
  end
  
  def enable_view_transactions_right
    view_transactions_right(true, params[:id], "a maintenant")
  end
  
  def disable_view_transactions_right
    view_transactions_right(false, params[:id], "n'a plus")
  end
  
  def view_transactions_right(status, id, message)
    @profile = Profile.find_by_id(id)
    @profile.update_attributes(view_transactions: status)
    
    redirect_to edit_profiles_rights_path, :notice => "Le profil #{@profile.name} #{message} le droit de visualiser les transactions."
  end
  
  def enable_disable_account_right
    disable_account_right(true, params[:id], "a maintenant")
  end
  
  def disable_disable_account_right
    disable_account_right(false, params[:id], "n'a plus")
  end
  
  def disable_account_right(status, id, message)
    @profile = Profile.find_by_id(id)
    @profile.update_attributes(disable_account: status)
    
    redirect_to edit_profiles_rights_path, :notice => "Le profil #{@profile.name} #{message} le droit d'activer/désactiver des comptes Paymoney."
  end
  
  def enable_disable_profile_right
    disable_profile_right(true, params[:id], "activé")
  end
  
  def disable_disable_profile_right
    disable_profile_right(false, params[:id], "désactivé")
  end
  
  def disable_profile_right(status, id, message)
    @profile = Profile.find_by_id(id)
    @profile.update_attributes(published: status)
    
    redirect_to profiles_path, :notice => "Le profil #{@profile.name} a été #{message}."
  end
  
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_profiles.html.erb
<table cellpadding = "0" cellspacing = "0" width = "100%" class = "table">
  <thead>
    <tr>
      <th width = "33%">Nom</th>
      <th width = "33%">Abbréviation</th>
      <th width = "34%">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if @profiles.blank? %>
			<tr>
				<td colspan = "3">Aucun profil présent dans la base de données</td>
			</tr>
		<% else %>
		  <% @profiles.each do |profile| %>		    
		    <tr>
		      <td>
		        <%= profile.name %>	
					</td>
					<td>
					  <%= profile.shortcut %>
					</td>
					<td>
					  <% if current_user.profile.edit_profile %>
					    <a title = "Modifier le profil" href = "<%= edit_profile_path(profile.id) %>" class = "button green">
					      <div class = "icon">			
					        <span class = "ico-pencil"></span>		    
					      </div>
					    </a>
					    <a title = "Modifier les droits" href = "/profiles/edit_rights" class = "button blue">
					      <div class = "icon">			
					        <span class = "ico-random"></span>		    
					      </div>
					    </a>	 
					    <% if (profile.published == true or profile.published == nil) %>                 
		            <%= link_to "<div class = 'icon'><span class = 'ico-cancel'></span></div>".html_safe, disable_disable_profile_right_path(profile.id), :class => "button red", :title => "Désactiver le profil", :confirm => "Êtes vous sûr de vouloir désactiver ce profil?" %>			            			            	            
		          <% else %>
		            <%= link_to "<div class = 'icon'><span class = 'ico-checkmark'></span></div>".html_safe, enable_disable_profile_right_path(profile.id), :class => "button green", :title => "Activer le profil", :confirm => "Êtes vous sûr de vouloir activer ce profil?" %>			            
		          <% end %>		
					  <% end %>    
					</td>
			  </tr>
			<% end %>
		<% end %>
  </tbody>
</table>	

app/views/profiles/auditor_index.html.erb
<div class="page-header">
    <div class="icon">
        <span class="ico-arrow-right"></span>
    </div>
    <h1>Profils <small>Créer un profil</small></h1>
</div>

<div class = "row-fluid">
  <div class = "span6">
    <%= render 'layouts/flash_messages' %>
    <% if !@error_messages.blank? %>  
      <div class = "alert alert-error">         
        <ul>
        <% @error_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% if !@alert_messages.blank? %>  
      <div class = "alert alert-info">         
        <% @alert_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
    <% if !@success_messages.blank? %> 
      <div class = "alert alert-success">         
        <% @success_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
     
    <div class = "block">
      <div class = "head">
        <div class = "icon">
          <span class = "ico-expand"></span>
        </div>
        <h2>Création de profil</h2>
      </div>
      <div class = "data-fluid">
        <%= form_tag ("/profile/create") do %>
          <%#= devise_error_messages! %>
          <div class = "<%= @namecss %>">
            <div class = "span3">Nom</div>
            <div class = "span9">	        
              <%= text_field_tag "name", params[:name], :placeholder => "Nom du profil" %>
            </div>
          </div>
          <div class = "<%= @shortcutcss %>">
            <div class = "span3">Abbréviation</div>
            <div class = "span9">	        
              <%= text_field_tag "shortcut", params[:shortcut], :placeholder => "Abbréviation du profil" %>
            </div>
          </div>          
          
          <% if current_user.profile.shortcut != "ADMIN-A" and current_user.profile.create_profile %>       
            <div class = "row-form">
              <div class="span9">
                <%= button_tag(:name => "Créer un profil", :data => {:disable_with => "Veuillez patienter"}, :class => "btn") do %>
                  Créer un profil <div class="icon-arrow-next icon-white"></div> 
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class = "span6">
    <div class = "block">
      <div class = "head">
        <div class = "icon">
          <span class = "ico-list-3"></span>
        </div>
        <h2>Liste des profils</h2>
      </div>
      <div class = "head blue" >
		    <div class = "icon" >
		      <span class = "ico-pen-2"></span>		      
		    </div>  
		    <h2>Visualisation des profils</h2>
		  </div>	
		  <table cellpadding = "0" cellspacing = "0" width = "100%" class = "table">
        <thead>
          <tr>
            <th width = "50%">Nom</th>
            <th width = "29%">Abbréviation</th>
            <th width = "21%">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% if @profiles.blank? %>
			      <tr>
				      <td colspan = "3">Aucun profil présent dans la base de données</td>
			      </tr>
		      <% else %>
		        <% @profiles.each do |profile| %>		    
		          <tr>
		            <td>
		              <%= link_to profile.name, users_per_profile_path(profile.id) %>	
		              <b>(<%= profile.users.count %>)</b>
					      </td>
					      <td>
					        <%= profile.shortcut %>
					      </td>
					      <td>
					        <% if current_user.profile.edit_profile %>
					          <a title = "Modifier le profil" href = "<%= edit_profile_path(profile.id) %>" class = "button green">
					            <div class = "icon">			
					              <span class = "ico-pencil"></span>		    
					            </div>
					          </a>
					          <a title = "Modifier les droits" href = "/profiles/edit_rights" class = "button blue">
					            <div class = "icon">			
					              <span class = "ico-random"></span>		    
					            </div>
					          </a>	
					        <% end %>    
					      </td>
			        </tr>
			      <% end %>
		      <% end %>
        </tbody>
      </table>	
 	 
		  <% unless @profiles.blank? %>
		    <div id = "pagination">
          <%= paginate @profiles, :params => { :controller => :profiles, :action => :index } %>
        </div>
      <% end %> 
    </div>
  </div>
</div>

app/views/profiles/custom_profiles.html.erb
<div class="page-header">
    <div class="icon">
      <span class="ico-arrow-right"></span>
    </div>
    <h1>Profil personnalisé <small>Vous avez accès à un ensemble de fonctionnalités prédéfinies par l'administrateur</small></h1>
</div>

<div class = "row-fluid">
  <div class = "span12">
    <%= render 'layouts/flash_messages' %>
    <div id = "custom_messages">
    </div>
    <% if !@error_messages.blank? %>  
      <div class = "alert alert-error">         
        <ul>
        <% @error_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% if !@alert_messages.blank? %>  
      <div class = "alert alert-info">         
        <% @alert_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
    <% if !@success_messages.blank? %> 
      <div class = "alert alert-success">         
        <% @success_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
     
    <div class = "block">      
      <div class = "data-fluid">
        <div class = "errorContainer"> 
          <h2>Bienvenue sur l'interface d'administration du HUB monétique</h2>
        </div>
      </div>
    </div>
  </div> 
</div>

app/views/profiles/edit_rights.html.erb
<script type="text/javascript" language="JavaScript">
  $(document).on('ready page:load', function(){  
    options =	{ 
			position : 'top',
			align	 : 'center',						
			innerHtmlStyle: {
								color:'#FFFFFF', 
								'text-align':'left',
								padding:'2px',
								'font-size':'13px'
							},																
			themeName: 	'all-grey',
			themePath: 	'../../../images/jquerybubblepopup-theme'
		};          
  });
</script>

<div class="page-header">
    <div class="icon">
      <span class="ico-arrow-right"></span>
    </div>
    <h1>Profils <small>Attribuer ou retirer des droits aux utilisateurs liés à ces profils</small></h1>
</div>

<div class = "row-fluid">
  <div class = "span12">
    <%= render 'layouts/flash_messages' %>
    <div id = "custom_messages">
    </div>
    <% if !@error_messages.blank? %>  
      <div class = "alert alert-error">         
        <ul>
        <% @error_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% if !@alert_messages.blank? %>  
      <div class = "alert alert-info">         
        <% @alert_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
    <% if !@success_messages.blank? %> 
      <div class = "alert alert-success">         
        <% @success_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
     
    <div class = "block">
      <div class = "head blue">
        <div class = "icon">
          <i class = "ico-layout-9"></i>
        </div>
        <h2>Liste des profils</h2>
        <ul class = "buttons">
          <li>
            <a href = "javascript:history.go(-1);" alt = "Aller à la page précédente">
              <div class = "icon">
                <span class = "ico-arrow-left">
                               
                </span>
              </div>
            </a>
          </li>
        </ul>
      </div>
      <div class = "data-fluid">
        <table class = "table" cellpading = "0" cellspacing = "0" width = "100%">
          <thead>
            <tr>
              <th width = "61%">
                Droits
              </th>
              <th width = "39%">
                Nom du profil
              </th>                           
            </tr>
          </thead>
          <tbody>
            <% if @profiles.blank? %>
              <tr>
                <td colspan = "2">Aucun profil à afficher</td>
              </tr>
            <% else %>
              <% @profiles.each do |profile| %>                
                <tr>                 
                  <td>
                    <% if profile.create_user == false or profile.create_user.blank? %>                  
					            <%= link_to "<div class = 'icon'><span class = 'ico-group'></span></div>".html_safe, enable_create_user_right_path(profile.id), :class => "button green", :id => "enable_create_user_#{profile.id}", :title => "Activer le droit de création d'utilisateurs", :confirm => "Êtes vous sûr de vouloir activer le droit de création d'utilisateurs?" %>					            
					          <% else %>
					            <%= link_to "<div class = 'icon'><span class = 'ico-group'></span></div>".html_safe, disable_create_user_right_path(profile.id), :class => "button red", :id => "disable_create_user_#{profile.id}", :title => "Désactiver le droit de création d'utilisateurs", :confirm => "Êtes vous sûr de vouloir désactiver le droit de création d'utilisateurs?" %>
					          <% end %>
					          
					          <% if profile.edit_user_data == false or profile.edit_user_data.blank? %>                  
					            <%= link_to "<div class = 'icon'><span class = 'ico-group'></span></div>".html_safe, enable_edit_user_data_right_path(profile.id), :class => "button blue", :id => "enable_edit_user_data_#{profile.id}", :title => "Activer le droit de modification de données utilisateur", :confirm => "Êtes vous sûr de vouloir activer le droit de modification de données utilisateurs?" %>					            
					          <% else %>
					            <%= link_to "<div class = 'icon'><span class = 'ico-group'></span></div>".html_safe, disable_edit_user_data_right_path(profile.id), :class => "button yellow", :id => "disable_edit_user_data_#{profile.id}", :title => "Désactiver le droit de modification de données utilisateur", :confirm => "Êtes vous sûr de vouloir désactiver le droit de modification de données utilisateurs?" %>
					          <% end %>
					          
					          <% if profile.create_profile == false or profile.create_profile.blank? %>                  
					            <%= link_to "<div class = 'icon'><span class = 'ico-user'></span></div>".html_safe, enable_create_profile_right_path(profile.id), :class => "button green", :id => "enable_create_profile_#{profile.id}", :title => "Activer le droit de création de profil utilisateur", :confirm => "Êtes vous sûr de vouloir activer le droit de création de profils?" %>					            
					          <% else %>
					            <%= link_to "<div class = 'icon'><span class = 'ico-user'></span></div>".html_safe, disable_create_profile_right_path(profile.id), :class => "button red", :id => "disable_create_profile_#{profile.id}", :title => "Désactiver le droit de création de profil utilisateur", :confirm => "Êtes vous sûr de vouloir désactiver le droit de création de profils?" %>
					          <% end %>
					          
					          <% if profile.edit_profile == false or profile.edit_profile.blank? %>                  
					            <%= link_to "<div class = 'icon'><span class = 'ico-user'></span></div>".html_safe, enable_edit_profile_right_path(profile.id), :title => "Activer le droit de création de profil utilisateur", :class => "button blue", :title => "Activer le droit de modification de profil utilisateur", :id => "enable_edit_profile_#{profile.id}", :confirm => "Êtes vous sûr de vouloir activer le droit de modification de profils?" %>					            
					          <% else %>
					            <%= link_to "<div class = 'icon'><span class = 'ico-user'></span></div>".html_safe, disable_edit_profile_right_path(profile.id), :class => "button yellow", :id => "disable_edit_profile_#{profile.id}", :title => "Désactiver le droit de modification de profil utilisateur", :confirm => "Êtes vous sûr de vouloir désactiver le droit de modification de profils?" %>
					          <% end %>	
					          
					          <% if profile.view_transactions == false or profile.view_transactions.blank? %>                  
					            <%= link_to "<div class = 'icon'><span class = 'ico-shopping-cart'></span></div>".html_safe, enable_view_transactions_right_path(profile.id), :class => "button green", :title => "Activer le droit de visualisation des transactions", :confirm => "Êtes vous sûr de vouloir activer le droit de visualisation des transactions?" %>					            
					          <% else %>
					            <%= link_to "<div class = 'icon'><span class = 'ico-shopping-cart'></span></div>".html_safe, disable_view_transactions_right_path(profile.id), :class => "button red", :title => "Désactiver le droit de visualisation des transactions", :confirm => "Êtes vous sûr de vouloir désactiver le droit de visualisation des transactions?" %>
					          <% end %>		
					          
					          <% if profile.disable_account == false or profile.disable_account.blank? %>                  
					            <%= link_to "<div class = 'icon'><span class = 'ico-remove-sign'></span></div>".html_safe, enable_disable_account_right_path(profile.id), :class => "button green", :title => "Activer le droit d'activation/désactivation de compte Paymoney", :confirm => "Êtes vous sûr de vouloir activer le droit d'activation/désactivation de compte Paymoney?" %>					            
					          <% else %>
					            <%= link_to "<div class = 'icon'><span class = 'ico-remove-sign'></span></div>".html_safe, disable_disable_account_right_path(profile.id), :class => "button red", :title => "Désactiver le droit d'activation/désactivation de compte Paymoney", :confirm => "Êtes vous sûr de vouloir désactiver le droit d'activation/désactivation de compte Paymoney?" %>
					          <% end %>				          					                
                  </td>   
                  <td>
                    <%= profile.name %>
                  </td>               
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <% unless @profiles.blank? %>
		      <div id = "pagination">
            <%= paginate @profiles, :params => { :controller => :profiles, :action => :edit_rights } %>
          </div>
        <% end %> 
      </div>
    </div>
  </div> 
</div>