config/routes.rb
PaymoneyAdministration::Application.routes.draw do
  root :to => redirect("/users/sign_in")
  
  resources :statuses
  
  
  devise_for :users, :controllers => {:registrations => "devise/registrations", :sessions => "devise/sessions", :passwords => "devise/passwords"}
  
  devise_scope :user do
  	get 'dashboard' => 'devise/registrations#new', :as => :administrator_dashboard
  	get "user/edit_profile/:id" => "devise/registrations#edit", :as => :edit_user_profile
  	patch 'user/update_profile' => 'devise/registrations#update_profile', :as => :update_user_profile
  end
  
  get 'user/search' => 'users#search', :as => :search_user
  get 'user/enable_profile/:id' => 'users#enable_profile', :as => :enable_user_profile
  get 'user/disable_profile/:id' => 'users#disable_profile', :as => :disable_user_profile 
  
  get "liste-des-comptes-actives" => "accounts#index", as: :enabled_accounts_list
  get "liste-des-comptes-desactives" => "accounts#disabled_accounts", as: :disabled_accounts_list
  get "liste-des-depots" => "accounts#credits", as: :list_credits
  get "liste-des-retraits" => "accounts#debits", as: :list_debits
  get "activer-un-compte/:account_id" => "accounts#enable_account", as: :enable_account
  get "desactiver-un-compte/:account_id" => "accounts#disable_account", as: :disable_account
  post "rechercher-un-compte" => "accounts#search"
  get "rechercher-un-compte" => "accounts#search"
  
  get "auditeur-liste-des-profils" => "profiles#auditor_index", as: :auditor_index
  get "liste-des-utilisateurs-par-profil/:profile_id" => "profiles#users_per_profile", as: :users_per_profile
  get "profile/custom" => "profiles#custom_profiles", as: :custom_profiles_dashboard
  get "profiles" => "profiles#index", as: :profiles
  post "profile/create" => "profiles#create"
  get "profile/create" => "profiles#index"
  get "profile/edit/:id" => "profiles#edit", as: :edit_profile
  post "profile/update" => "profiles#update"
  get "profile/update" => "profiles#index"
  get "profiles/edit_rights" => "profiles#edit_rights", as: :edit_profiles_rights
  get "profile/right/enable_create_user/:id" => "profiles#enable_create_user_right", as: :enable_create_user_right
  get "profile/right/disable_create_user/:id" => "profiles#disable_create_user_right", as: :disable_create_user_right
  get "profile/right/enable_edit_user_data/:id" => "profiles#enable_edit_user_data_right", as: :enable_edit_user_data_right
  get "profile/right/disable_edit_user_data/:id" => "profiles#disable_edit_user_data_right", as: :disable_edit_user_data_right
  
  get "profile/right/enable_create_profile/:id" => "profiles#enable_create_profile_right", as: :enable_create_profile_right
  get "profile/right/disable_create_profile/:id" => "profiles#disable_create_profile_right", as: :disable_create_profile_right
  
  get "profile/right/enable_edit_profile/:id" => "profiles#enable_edit_profile_right", as: :enable_edit_profile_right
  get "profile/right/disable_edit_profile/:id" => "profiles#disable_edit_profile_right", as: :disable_edit_profile_right
  
  get "profile/right/enable_view_transactions/:id" => "profiles#enable_view_transactions_right", as: :enable_view_transactions_right
  get "profile/right/disable_view_transactions/:id" => "profiles#disable_view_transactions_right", as: :disable_view_transactions_right
  
  get "profile/right/enable_disable_account/:id" => "profiles#enable_disable_account_right", as: :enable_disable_account_right
  get "profile/right/disable_disable_account/:id" => "profiles#disable_disable_account_right", as: :disable_disable_account_right
  
  get "profile/right/enable_disable_profile/:id" => "profiles#enable_disable_profile_right", as: :enable_disable_profile_right
  get "profile/right/disable_disable_profile/:id" => "profiles#disable_disable_profile_right", as: :disable_disable_profile_right
  

  

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>    
  <%# if value.eql?(true) %>
    <div class="<%= flash_class(key) %> fade in">      
      <%= value %>
    </div>
  <%# end %>
<% end %>

app/views/layouts/administrator.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paymoney || Administrateur::Paramétrages</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "stylesheets", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "jquery.bubblepopup.v2.3.1", media: "all", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "plugins/jquery/jquery-1.9.1.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jquery/jquery-ui-1.10.1.custom.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.easing", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.collapse", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.bubblepopup.v2.3.1.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/jquery/jquery-migrate-1.1.1.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jquery/globalize", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/other/excanvas", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/other/jquery.mousewheel.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/bootstrap/bootstrap.min", "data-turbolinks-track" => true %>    
  
  <%= javascript_include_tag "plugins/cookies/jquery.cookies.2.2.0.min", "data-turbolinks-track" => true %>  
  
  <%#= javascript_include_tag "plugins/animatedprogressbar/animated_progressbar", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "plugins/jflot/jquery.flot", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "plugins/jflot/jquery.flot.stack", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "plugins/jflot/jquery.flot.pie", "data-turbolinks-track" => true %>
  
  <%#= javascript_include_tag "plugins/sparklines/jquery.sparkline.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/mcustomscrollbar/jquery.mCustomScrollbar.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/uniform/jquery.uniform.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/select/select2.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/tagsinput/jquery.tagsinput.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/maskedinput/jquery.maskedinput-1.3.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/multiselect/jquery.multi-select.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/shbrush/XRegExp", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shCore", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushXml", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushJScript", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushCss", "data-turbolinks-track" => true %>   
  
  <%= javascript_include_tag "plugins", "data-turbolinks-track" => true %> 
  <%= javascript_include_tag "charts", "data-turbolinks-track" => true %> 
  
  <%= javascript_include_tag "actions", "data-turbolinks-track" => true %> 
  
  <%= csrf_meta_tags %>
</head>

<body>
	<div class = "wrapper">
	
		<!------------------------------------------ Sidebar ----------------------------------->
		<div class = "sidebar">		
			<div class="top">
		    <!--<span class="petroci_logo"></span>-->
		  </div>
		  <div class="nContainer">                
        <ul class="navigation bordered">         
          <li class="active"><%= link_to "Profils", profiles_path, class: "blblue" %></li>  
          <!--<li class="active"><%= link_to "Comptes", enabled_accounts_list_path, class: "blyellow" %></li>   -->                        
        </ul>
        <a class="close">
          <span class="ico-remove"></span>
        </a>
    	</div>		  
		</div>
		<!------------------------------------------ Sidebar ----------------------------------->
		
		<!------------------------------------------ Body ----------------------------------->
		<div class = "body">
		
			<!------------------------------------------ Navigation ----------------------------------->
			<ul class="navigation">
        <li>
          <a href="<%= profiles_path %>" class="button">
            <div class="icon">
              <span class="ico-user"></span>
            </div>                    
            <div class="name">Profils</div>
          </a>                
        </li> 
       <!-- <li>
          <a href="<%= enabled_accounts_list_path %>" class="button yellow">
            <div class="icon">
              <span class="ico-profile"></span>
            </div>                    
            <div class="name">Comptes</div>
          </a>                
        </li>     -->            
        <li>
          <div class="user">
            <a href="#" class="name">
              <span><%= current_user.full_name %></span>
              <span class="cblue"><%= current_user.profile_name %></span>
            </a>
          </div>
          <div class="buttons">
            <!--<div class="sbutton green navButton">
              <a href="#"><span class="ico-align-justify"></span></a>
            </div>-->
            <div class="sbutton blue">
              <%= link_to "<span class='ico-off'></span>".html_safe, destroy_user_session_path, :method => :delete %>
           
            </div>                        
          </div>
        </li>                   
      </ul>
      <!------------------------------------------ Navigation ----------------------------------->
      
      <!------------------------------------------ Content ----------------------------------->
      <div class = "content">
      	<%= yield %>
      </div>
      <!------------------------------------------ Content ----------------------------------->
      
		</div>
		<!------------------------------------------ Body ----------------------------------->
		  
	</div>
		

</body>
</html>

app/views/layouts/administrator_auditor.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paymoney || Administrateur::Auditeur</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "stylesheets", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "jquery.bubblepopup.v2.3.1", media: "all", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "plugins/jquery/jquery-1.9.1.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jquery/jquery-ui-1.10.1.custom.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.easing", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.collapse", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.bubblepopup.v2.3.1.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/jquery/jquery-migrate-1.1.1.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jquery/globalize", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/other/excanvas", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/other/jquery.mousewheel.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/bootstrap/bootstrap.min", "data-turbolinks-track" => true %>    
  
  <%= javascript_include_tag "plugins/cookies/jquery.cookies.2.2.0.min", "data-turbolinks-track" => true %>  
  
  <%#= javascript_include_tag "plugins/animatedprogressbar/animated_progressbar", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "plugins/jflot/jquery.flot", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "plugins/jflot/jquery.flot.stack", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "plugins/jflot/jquery.flot.pie", "data-turbolinks-track" => true %>
  
  <%#= javascript_include_tag "plugins/sparklines/jquery.sparkline.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/mcustomscrollbar/jquery.mCustomScrollbar.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/uniform/jquery.uniform.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/select/select2.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/tagsinput/jquery.tagsinput.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/maskedinput/jquery.maskedinput-1.3.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/multiselect/jquery.multi-select.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/shbrush/XRegExp", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shCore", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushXml", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushJScript", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushCss", "data-turbolinks-track" => true %>   
  
  <%= javascript_include_tag "plugins", "data-turbolinks-track" => true %> 
  <%= javascript_include_tag "charts", "data-turbolinks-track" => true %> 
  
  <%= javascript_include_tag "actions", "data-turbolinks-track" => true %> 
  
  <%= csrf_meta_tags %>
</head>

<body>
	<div class = "wrapper">
	
		<!------------------------------------------ Sidebar ----------------------------------->
		<div class = "sidebar">		
			<div class="top">
		    <!--<span class="petroci_logo"></span>-->
		  </div>
		  <div class="nContainer">                
        <ul class="navigation bordered">   
          <li><%= link_to "Profils", auditor_index_path, class: "blblue" %></li>               
          <li class="active"><%= link_to "Comptes", enabled_accounts_list_path, class: "blgreen" %></li>                          
        </ul>
        <a class="close">
          <span class="ico-remove"></span>
        </a>
    	</div>		  
		</div>
		<!------------------------------------------ Sidebar ----------------------------------->
		
		<!------------------------------------------ Body ----------------------------------->
		<div class = "body">
		
			<!------------------------------------------ Navigation ----------------------------------->
			<ul class="navigation">
			  <li>
          <a href="<%= auditor_index_path %>" class="button blue">
            <div class="icon">
              <span class="ico-profile"></span>
            </div>                    
            <div class="name">Profils</div>
          </a>                
        </li>
        <li>
          <a href="<%= enabled_accounts_list_path %>" class="button green">
            <div class="icon">
              <span class="ico-profile"></span>
            </div>                    
            <div class="name">Comptes</div>
          </a>                
        </li>                    
        <li>
          <div class="user">
            
            <!--<%= image_tag("examples/users/dmitry_m.jpg", align: "left") %>-->
            <a href="#" class="name">
              <span><%= current_user.full_name %></span>
              <span class="cblue"><%= current_user.profile_name %></span>
            </a>
          </div>
          <div class="buttons">
            <!--<div class="sbutton green navButton">
              <a href="#"><span class="ico-align-justify"></span></a>
            </div>-->
            <div class="sbutton blue">
              <%= link_to "<span class='ico-off'></span>".html_safe, destroy_user_session_path, :method => :delete %>
           
            </div>                        
          </div>
        </li>                   
      </ul>
      <!------------------------------------------ Navigation ----------------------------------->
      
      <!------------------------------------------ Content ----------------------------------->
      <div class = "content">
      	<%= yield %>
      </div>
      <!------------------------------------------ Content ----------------------------------->
      
		</div>
		<!------------------------------------------ Body ----------------------------------->
		  
	</div>
		

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyProfiler</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if user_signed_in? %>	
	<div style = "float:right;">
		<p>
			<%= current_user.short_profile %> 
			<%= link_to "Dashboard", administrator_dashboard_path %> |  
			<%= link_to "Profile", edit_user_profile_path(current_user.id) %> | 
			<%= link_to "Logout", destroy_user_session_path, :method =>  :delete %> |
			<%= link_to "Search", search_user_path %>
		</p>
	</div>
<% end %>


<%= yield %>

</body>
</html>

app/views/layouts/custom_profiles.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paymoney || <%= current_user.profile_name %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "stylesheets", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "jquery.bubblepopup.v2.3.1", media: "all", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "plugins/jquery/jquery-1.9.1.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jquery/jquery-ui-1.10.1.custom.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.easing", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.collapse", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.bubblepopup.v2.3.1.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/jquery/jquery-migrate-1.1.1.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jquery/globalize", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/other/excanvas", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/other/jquery.mousewheel.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/bootstrap/bootstrap.min", "data-turbolinks-track" => true %>    
  
  <%= javascript_include_tag "plugins/cookies/jquery.cookies.2.2.0.min", "data-turbolinks-track" => true %>  
  
  <%#= javascript_include_tag "plugins/animatedprogressbar/animated_progressbar", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "plugins/jflot/jquery.flot", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "plugins/jflot/jquery.flot.stack", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "plugins/jflot/jquery.flot.pie", "data-turbolinks-track" => true %>
  
  <%#= javascript_include_tag "plugins/sparklines/jquery.sparkline.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/mcustomscrollbar/jquery.mCustomScrollbar.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/uniform/jquery.uniform.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/select/select2.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/tagsinput/jquery.tagsinput.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/maskedinput/jquery.maskedinput-1.3.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/multiselect/jquery.multi-select.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/shbrush/XRegExp", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shCore", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushXml", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushJScript", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushCss", "data-turbolinks-track" => true %>   
  
  <%= javascript_include_tag "plugins", "data-turbolinks-track" => true %> 
  <%= javascript_include_tag "charts", "data-turbolinks-track" => true %> 
  
  <%= javascript_include_tag "actions", "data-turbolinks-track" => true %> 
  
  <%= csrf_meta_tags %>
</head>

<body>
	<div class = "wrapper">
	
		<!------------------------------------------ Sidebar ----------------------------------->
		<div class = "sidebar">		
			<div class="top">
		    <!--<span class="petroci_logo"></span>-->
		  </div>
		  <div class="nContainer">                
        <ul class="navigation bordered">
          <% @profile = current_user.profile %>
          <% if (@profile.published == true or @profile.published == nil) %>
            <% if @profile.create_user or @profile.edit_user_data %>         
              <li class="active"><%= link_to "Utilisateurs", administrator_dashboard_path, class: "blblue" %></li>
            <% end %>
            <% if @profile.create_profile or @profile.edit_profile %>
              <li class="active"><%= link_to "Profils", profiles_path, class: "blyellow" %></li>
            <% end %>
            <% if @profile.view_transactions or @profile.disable_account %>
              <li class="active"><%= link_to "Comptes", enabled_accounts_list_path, class: "blgreen" %></li>
            <% end %>
          <% end %>
          <!--<li>
            <a href="#" class="blblue">Paramètres</a>
            <div class="open"></div>
            <ul>
              <li><%#= link_to "Types d'ayants droits", inheritor_types_path %></li>  
              <li><%#= link_to "Types de banques", bank_types_path %></li> 
              <li><%#= link_to "Frais de transport", payment_way_fees_path %></li>              
            </ul>
          </li>-->
          
          <!--
          <li><a href="statistic.html" class="blred">Paramètres</a></li>  -->                    
        </ul>
        <a class="close">
          <span class="ico-remove"></span>
        </a>
    	</div>		  
		</div>
		<!------------------------------------------ Sidebar ----------------------------------->
		
		<!------------------------------------------ Body ----------------------------------->
		<div class = "body">
		
			<!------------------------------------------ Navigation ----------------------------------->
			<ul class="navigation">

			  <% if (@profile.published == true or @profile.published == nil) %>
          <% if @profile.create_user or @profile.edit_user_data %>     
            <li>
              <a href="<%= administrator_dashboard_path %>" class="button">
                <div class="icon">
                  <span class="ico-monitor"></span>
                </div>                    
                <div class="name">Utilisateurs</div>
              </a>                
            </li>
          <% end %> 
          <% if @profile.create_profile or @profile.edit_profile %>
            <li>
              <a href="<%= profiles_path %>" class="button yellow">
                <div class="icon">
                  <span class="ico-user"></span>
                </div>                    
                <div class="name">Profils</div>
              </a>                
            </li>
          <% end %>
          <% if @profile.view_transactions or @profile.disable_account %>
            <li>
              <a href="<%= enabled_accounts_list_path %>" class="button green">
                <div class="icon">
                  <span class="ico-user"></span>
                </div>                    
                <div class="name">Comptes</div>
              </a>                
            </li>
          <% end %>
        <% end %>
        <!--                    
        <li>
          <a href="#" class="button green">
            <div class="arrow"></div>
            <div class="icon">
              <span class="ico-pen-2"></span>
            </div>                    
            <div class="name">News</div>
          </a>                
          <ul class="sub">
            <li><%= link_to "Envoi", "#" %></li>
            <li><%= link_to "Historique", "#" %></li>
            <li><%= link_to "Statistiques", "#" %></li>
          </ul>                    
        </li>                                               
        <li>
          <a href="#" class="button dblue">
            <div class="arrow"></div>
            <div class="icon">
              <span class="ico-layout-7"></span>
            </div>                    
            <div class="name">Abonnés</div>
          </a> 
          <ul class="sub">
            <li><a href="tables.html">Suspendre</a></li>
            <li><a href="tables_dynamic.html">Rechercher</a></li>
          </ul>                                        
        </li>
        <li>
          <a href="statistic.html" class="button red">
            <div class="icon">
              <span class="ico-chart-4"></span>
            </div>                    
            <div class="name">Paramètres</div>
          </a>                
        </li> -->                                
        <li>
          <div class="user">
            
            <!--<%= image_tag("examples/users/dmitry_m.jpg", align: "left") %>-->
            <a href="#" class="name">
              <span><%= current_user.full_name %></span>
              <span class="cblue"><%= current_user.profile_name %></span>
            </a>
          </div>
          <div class="buttons">
            <!--<div class="sbutton green navButton">
              <a href="#"><span class="ico-align-justify"></span></a>
            </div>-->
            <div class="sbutton blue">
              <%= link_to "<span class='ico-off'></span>".html_safe, destroy_user_session_path, :method => :delete %>
           
            </div>                        
          </div>
        </li>                   
      </ul>
      <!------------------------------------------ Navigation ----------------------------------->
      
      <!------------------------------------------ Content ----------------------------------->
      <div class = "content">
      	<%= yield %>
      </div>
      <!------------------------------------------ Content ----------------------------------->
      
		</div>
		<!------------------------------------------ Body ----------------------------------->
		  
	</div>
		

</body>
</html>