config/routes.rb
PaymoneyAdministration::Application.routes.draw do
  root :to => redirect("/users/sign_in")
  
  resources :statuses
  
  
  devise_for :users, :controllers => {:registrations => "devise/registrations", :sessions => "devise/sessions", :passwords => "devise/passwords"}
  
  devise_scope :user do
  	get 'dashboard' => 'devise/registrations#new', :as => :administrator_dashboard
  	get "user/edit_profile/:id" => "devise/registrations#edit", :as => :edit_user_profile
  	patch 'user/update_profile' => 'devise/registrations#update_profile', :as => :update_user_profile
  end
  
  get 'user/search' => 'users#search', :as => :search_user
  get 'user/enable_profile/:id' => 'users#enable_profile', :as => :enable_user_profile
  get 'user/disable_profile/:id' => 'users#disable_profile', :as => :disable_user_profile 
  
  get "liste-des-comptes-actives" => "accounts#index", as: :enabled_accounts_list
  get "liste-des-comptes-desactives" => "accounts#disabled_accounts", as: :disabled_accounts_list
  get "liste-des-depots" => "accounts#credits", as: :list_credits
  get "liste-des-retraits" => "accounts#debits", as: :list_debits
  get "activer-un-compte/:account_id" => "accounts#enable_account", as: :enable_account
  get "desactiver-un-compte/:account_id" => "accounts#disable_account", as: :disable_account
  post "rechercher-un-compte" => "accounts#search"
  get "rechercher-un-compte" => "accounts#search"
  
  get "auditeur-liste-des-profils" => "profiles#auditor_index", as: :auditor_index
  get "liste-des-utilisateurs-par-profil/:profile_id" => "profiles#users_per_profile", as: :users_per_profile
  get "profile/custom" => "profiles#custom_profiles", as: :custom_profiles_dashboard
  get "profiles" => "profiles#index", as: :profiles
  post "profile/create" => "profiles#create"
  get "profile/create" => "profiles#index"
  get "profile/edit/:id" => "profiles#edit", as: :edit_profile
  post "profile/update" => "profiles#update"
  get "profile/update" => "profiles#index"
  get "profiles/edit_rights" => "profiles#edit_rights", as: :edit_profiles_rights
  get "profile/right/enable_create_user/:id" => "profiles#enable_create_user_right", as: :enable_create_user_right
  get "profile/right/disable_create_user/:id" => "profiles#disable_create_user_right", as: :disable_create_user_right
  get "profile/right/enable_edit_user_data/:id" => "profiles#enable_edit_user_data_right", as: :enable_edit_user_data_right
  get "profile/right/disable_edit_user_data/:id" => "profiles#disable_edit_user_data_right", as: :disable_edit_user_data_right
  
  get "profile/right/enable_create_profile/:id" => "profiles#enable_create_profile_right", as: :enable_create_profile_right
  get "profile/right/disable_create_profile/:id" => "profiles#disable_create_profile_right", as: :disable_create_profile_right
  
  get "profile/right/enable_edit_profile/:id" => "profiles#enable_edit_profile_right", as: :enable_edit_profile_right
  get "profile/right/disable_edit_profile/:id" => "profiles#disable_edit_profile_right", as: :disable_edit_profile_right
  
  get "profile/right/enable_view_transactions/:id" => "profiles#enable_view_transactions_right", as: :enable_view_transactions_right
  get "profile/right/disable_view_transactions/:id" => "profiles#disable_view_transactions_right", as: :disable_view_transactions_right
  
  get "profile/right/enable_disable_account/:id" => "profiles#enable_disable_account_right", as: :enable_disable_account_right
  get "profile/right/disable_disable_account/:id" => "profiles#disable_disable_account_right", as: :disable_disable_account_right
  
  get "profile/right/enable_disable_profile/:id" => "profiles#enable_disable_profile_right", as: :enable_disable_profile_right
  get "profile/right/disable_disable_profile/:id" => "profiles#disable_disable_profile_right", as: :disable_disable_profile_right
  

  

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  @@parameters = Parameter.first  
  
  before_filter :sign_out_disabled_users
  prepend_before_filter :authenticate_user!
  
  layout :layout_used
  
  def index
    @error_messages = []
    @enabled_accounts = get_enabled_or_disabled_accounts("1")
  end
  
  def disabled_accounts
    @error_messages = []
    @disabled_accounts = get_enabled_or_disabled_accounts("2")
  end
  
  def get_enabled_or_disabled_accounts(status)
    # communication with back office
    @request = Typhoeus::Request.new(URI.escape("#{@@parameters.back_office_url}/PAYMONEY-NGSER/rest/BACKOFFICECompteList/GetAllCompte/#{status}"), followlocation: true)        
    @internal_com_request = "@response = request.response.body"        
    run_typhoeus_request(@request, @internal_com_request)
    if !@response.blank?
      if @response.match(/\[\{\"idCompte/).blank?
          @accounts = JSON.parse(@response.sub(/\:/, ":[").sub(/\}\}$/, "}]}"))
        unless @accounts.blank?
          @accounts = Kaminari.paginate_array(@accounts["compte"]).page(params[:page]).per(10)
        end
      else
        @accounts = JSON.parse(@response)
        unless @accounts.blank?
          @accounts = Kaminari.paginate_array(@accounts["compte"]).page(params[:page]).per(10)
        end
      end
    end
    
    @accounts
  end
  
  def credits
    # status = 1
    @account = search_account(params[:email])
    @operations = get_credit_or_debit_operations(@account["idCompte"], 1)
  end
  
  def debits
    # status = 2
    @account = search_account(params[:email])
    @operations = get_credit_or_debit_operations(@account["idCompte"], 2)
  end
  
  def get_credit_or_debit_operations(account_id, status)
    @connexion = ActiveRecord::Base.establish_connection(
      :adapter  => "mysql",
      :host     => "localhost",
      :port     => 3306,
      :encoding => "utf8",
      :username => "root",
      :password => "jason",
      :database => "PayMoneyDB"
    )    
    @results = @connexion.connection.execute("SELECT * FROM operation WHERE type_oper_idtype_oper = #{status} AND Compte_idCompte = #{account_id}")
    
    @connexion = ActiveRecord::Base.establish_connection(
      :adapter  => "postgresql",
      :host     => "localhost",
      :port     => 5432,
      :encoding => "utf8",
      :username => "o1",
      :password => "com99123",
      :database => "PaymoneyAdministration_development"
    )
    @results = Kaminari.paginate_array(@results.to_a).page(params[:page]).per(10)
    @results
  end
  
  def enable_account
	  enable_disable_account(params[:account_id], true, "activé", "UnCompte", "1")
	end
	
	def disable_account
	  enable_disable_account(params[:account_id], false, "désactivé", "LKC", "2")
	end
	
	def enable_disable_account(id, bool, status, custom_link, expected_response)
	  @error_messages = []
	  @message = ""
	  
	  @request = Typhoeus::Request.new(URI.escape("#{@@parameters.back_office_url}/PAYMONEY-NGSER/rest/BACKOFFICECompteList/#{custom_link}/#{id}"), followlocation: true)        
    @internal_com_request = "@response = request.response.body"        
    run_typhoeus_request(@request, @internal_com_request)
    
    @status = JSON.parse(@response)
    if @status["idStatus"] == expected_response
      @message = "Le compte ayant pour numéro: #{id} a été #{status}"
    else
      @message = "Une erreur s'est produite, veuillez contacter l'administrateur."
    end
	  
	  redirect_to :back, :notice => @message
	end
	
	def search
	  @error_messages = []
	  @terms = params[:terms]
	  
	  if @terms.blank?
	    @error_messages << "Aucun terme de recherche n'a été entré."
	  else 
	    # communication with back office
      @request = Typhoeus::Request.new(URI.escape("#{@@parameters.back_office_url}/PAYMONEY-NGSER/rest/BACKOFFICECompteList/GetAllCompte_All_MUTI_CRITERE/#{@terms}"), followlocation: true)        
      @internal_com_request = "@response = request.response.body"        
      run_typhoeus_request(@request, @internal_com_request)
      if !@response.blank?
        if @response.match(/\[\{\"idCompte/).blank?
          @accounts = JSON.parse(@response.sub(/\:/, ":[").sub(/\}\}$/, "}]}"))
          unless @accounts.blank?
            @accounts = Kaminari.paginate_array(@accounts["compte"]).page(params[:page]).per(10)
          end
        else
          @accounts = JSON.parse(@response)
          unless @accounts.blank?
            @accounts = Kaminari.paginate_array(@accounts["compte"]).page(params[:page]).per(10)
          end
        end
      end
    end
	end
	
	def search_account(terms)
	  @error_messages = []
	  @account = nil
	  @request = Typhoeus::Request.new(URI.escape("#{@@parameters.back_office_url}/PAYMONEY-NGSER/rest/BACKOFFICECompteList/GetAllCompte_All_MUTI_CRITERE/#{terms}"), followlocation: true)        
    @internal_com_request = "@response = request.response.body"        
    run_typhoeus_request(@request, @internal_com_request)
    if !@response.blank?
      @accounts = JSON.parse(@response.sub(/\:/, ":[").sub(/\}\}$/, "}]}")).first[1].first
    end
    @accounts
	end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_accounts.html.erb
<div class = "head <%= @head_color %>" >
  <div class = "icon" >
    <span class = "ico-list-3"></span>		      
  </div>  
  <h2>Liste des comptes <%= @head_status %></h2>
  <ul class = "buttons">
    <li>
      <a href = "javascript:history.go(-1);" alt = "Aller à la page précédente">
        <div class = "icon">
          <span class = "ico-arrow-left">
                         
          </span>
        </div>
      </a>
    </li>
  </ul>
</div>
<div class = "data-fluid">
  <div id="DataTables_Table_1_wrapper" class="dataTables_wrapper" role="grid">
    <div class="dataTables_filter" id="DataTables_Table_1_filter" style = "float:left;margin: 5px 0px 10px 0px;">
      <%= form_tag ("/rechercher-un-compte") do %>
        <label>
          <b>Recherche:</b>          
          <%= text_field_tag "terms", params[:terms], :placeholder => "Termes de recherche" %>    
        </label>
      <% end %>
    </div>  
    <table width="100%" class="table tickets">
      <tbody>
        <% if @accounts.blank? %>
          <tr>
            <td colspan = "4">Aucun résultat à afficher</td>
          </tr>
        <% else %>
          <% @accounts.each do |account| %>
            <tr>
              <td width="20%" class="<%= @line_color %>">
                <span class="label <%= @label %>"><%= account["compteNumero"] %></span>
              </td>
              <td width="20%">
                <%= account["compteMontant"] %> FCFA <span class="mark">Né le <%= DateTime.parse(account["compteDate"]).strftime("%d/%m/%Y") %></span>
              </td>
              <td width="30%">
                <a class="<%= @name_color %>"><b><%= account["comptePrenom"] %> <%= account["compteNom"] %></b></a> <span class="mark"><%= account["compteEmail"] %></span>
              </td>    
              <td width="15%">
                <b>Contact: </b><%= account["comptePhone"] %>
              </td> 
              <td width="15%">
                <% if current_user.profile.view_transactions == true %>
                  <a title= "Liste des dépôts" href = "/liste-des-depots?account_id=<%= account['idCompte'] %>&email=<%= account['compteEmail'] %>" class = "button green">
					          <div class = "icon">			
					            <span class = "ico-money-bag"></span>		    
					          </div>
					        </a>
					        <a title= "Liste des retraits" href = "/liste-des-retraits?account_id=<%= account['idCompte'] %>&email=<%= account['compteEmail'] %>" class = "button purple">
					          <div class = "icon">			
					            <span class = "ico-money"></span>		    
					          </div>
					        </a>
					      <% end %>
					      <% if current_user.profile.disable_account == true %>
				          <% if @head_status == "désactivés" %>
			              <%= link_to "<div class = 'icon'><span class = 'ico-checkmark'></span></div>".html_safe, enable_account_path(account["compteNumero"]), :class => "button green", :confirm => "Êtes vous sûr de vouloir activer ce compte?", :title => "Activer le compte" %>				        
			            <% else %>
			              <%= link_to "<div class = 'icon'><span class = 'ico-remove'></span></div>".html_safe, disable_account_path(account["compteNumero"]), :class => "button red", :confirm => "Êtes vous sûr de vouloir désactiver ce compte?", :title => "Désactiver le compte" %>
			            <% end %>
			          <% end %>
              </td>                                   
            </tr> 
          <% end %>
        <% end %>                                                                                     
      </tbody>
    </table>                    
    <% unless @accounts.blank? %>
      <div id = "pagination">
        <%= paginate @accounts, :params => { :controller => :accounts, :action => @action.to_sym } %>
      </div>
    <% end %>
  </div>
</div>

app/views/accounts/_transactions.html.erb
<div class="block">
  <div class="head <%= @head_color %>">
    <div class="icon"><span class="ico-brush"></span></div>
    <h2>Numéro de compte: 
      <span class="<%= @label %>">
        <%= @account['compteNumero'] %>
      </span>
      Solde du compte:
      <span class="<%= @label %>">
        <%= @account['compteMontant'] %> FCFA
      </span> 
    </h2>    
    <ul class = "buttons">
    <li>
      <a href = "javascript:history.go(-1);" alt = "Aller à la page précédente">
        <div class = "icon">
          <span class = "ico-arrow-left">
                         
          </span>
        </div>
      </a>
    </li>
  </ul>                                                          
  </div>                
  <div class="data-fluid">
    <table cellpadding="0" cellspacing="0" width="100%" class="table table-hover">
      <thead>
        <tr>
          <th width="20%">
            Identifiant de transaction
          </th>
          <th width="40%">
            Montant de la transaction
          </th>
          <th width="40%">
            Date et heure de la transaction
          </th>
        </tr>
      </thead>
      <tbody>
        <% if @operations.blank? %>
          <tr>
            <td colspan = "4">Aucun résultat à afficher</td>
          </tr>
        <% else %>
          <% @operations.each do |operation| %>
            <tr>
              <td>
                <%= operation[0] %>
              </td>
              <td>
                <%= operation[2] %> FCFA
              </td>
              <td>
                Le <%= DateTime.parse(operation[1]).strftime("%d/%m/%y") %> à <%= DateTime.parse(operation[1]).strftime("%H:%M:%S") %>
              </td>                             
            </tr>  
          <% end %>
        <% end %>                        
      </tbody>
    </table>
    <% unless @operations.blank? %>
      <div id = "pagination">
        <%= paginate @operations, :params => { :controller => :accounts, :action => @action.to_sym, :email => @account['compteEmail'] } %>
      </div>
    <% end %>
  </div>                
</div>

app/views/accounts/credits.html.erb
<div class="page-header">
    <div class="icon">
        <span class="ico-arrow-right"></span>
    </div>
    <h1>Liste des dépôts de <%= "#{@account['comptePrenom']} #{@account['compteNom']}" %> <small>Affichage de la liste des transactions de dépôt ayant eu lieu sur le compte</small></h1>
</div>

<div class = "row-fluid">
  <div class = "span12">
    <%= render 'layouts/flash_messages' %>
    <% if !@error_messages.blank? %>  
      <div class = "alert alert-error">         
        <ul>
        <% @error_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% if !@alert_messages.blank? %>  
      <div class = "alert alert-info">         
        <% @alert_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
    <% if !@success_messages.blank? %> 
      <div class = "alert alert-success">         
        <% @success_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
        
  <div class="block">  

          <%
          @head_color = "green"          
          @label = "label"
          @action = "credits"
        %>
          <%= render partial: "transactions", :locals => {:head_color => @head_color, :accounts => @accounts, :label => @label, :action => @action} %> 

  </div>
</div>

app/views/accounts/debits.html.erb
<div class="page-header">
    <div class="icon">
        <span class="ico-arrow-right"></span>
    </div>
    <h1>Liste des retraits de <%= "#{@account['comptePrenom']} #{@account['compteNom']}" %> <small>Affichage de la liste des transactions de retrait ayant eu lieu sur le compte</small></h1>
</div>

<div class = "row-fluid">
  <div class = "span12">
    <%= render 'layouts/flash_messages' %>
    <% if !@error_messages.blank? %>  
      <div class = "alert alert-error">         
        <ul>
        <% @error_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% if !@alert_messages.blank? %>  
      <div class = "alert alert-info">         
        <% @alert_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
    <% if !@success_messages.blank? %> 
      <div class = "alert alert-success">         
        <% @success_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
        
  <div class="block">  

          <%
          @head_color = "purple"
          @label = "label"
          @action = "debits"
        %>
          <%= render partial: "transactions", :locals => {:head_color => @head_color, :accounts => @accounts, :label => @label, :action => @action} %> 

  </div>
</div>

app/views/accounts/disabled_accounts.html.erb
<div class="page-header">
    <div class="icon">
        <span class="ico-arrow-right"></span>
    </div>
    <h1>Liste des comptes désactivés <small>Affichage de la liste des comptes désactivés</small></h1>
</div>

<div class = "row-fluid">
  <div class = "span12">
    <%= render 'layouts/flash_messages' %>
    <% if !@error_messages.blank? %>  
      <div class = "alert alert-error">         
        <ul>
        <% @error_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% if !@alert_messages.blank? %>  
      <div class = "alert alert-info">         
        <% @alert_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
    <% if !@success_messages.blank? %> 
      <div class = "alert alert-success">         
        <% @success_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
        
  <div class="block">  
    <div class="data-fluid tabbable">                    
      <ul class="nav nav-tabs">
        <li class=""><a data-toggle="" href="<%= enabled_accounts_list_path %>"><b>Comptes activés</b></a></li>
        <li class="active"><a data-toggle="tab" href="#disabled"><b>Comptes désactivés</b></a></li>
      </ul>
      <div class="tab-content">
        <div id="disabled" class="tab-pane active">
          <%
          @head_color = "red"
          @head_status = "désactivés"
          @label = "label-important"
          @line_color = "bl_red"
          @name_color = "cred"
          @accounts = @disabled_accounts
          @action = "disabled_accounts"
        %>
          <%= render partial: "accounts", :locals => {:head_color => @head_color, :head_status => @head_status, :accounts => @accounts, :label => @label, :line_color => @line_color, :name_color => @name_color, :action => @action} %> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/index.html.erb
<div class="page-header">
    <div class="icon">
        <span class="ico-arrow-right"></span>
    </div>
    <h1>Liste des comptes activés <small>Affichage de la liste des comptes activés</small></h1>
</div>

<div class = "row-fluid">
  <div class = "span12">
    <%= render 'layouts/flash_messages' %>
    <% if !@error_messages.blank? %>  
      <div class = "alert alert-error">         
        <ul>
        <% @error_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% if !@alert_messages.blank? %>  
      <div class = "alert alert-info">         
        <% @alert_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
    <% if !@success_messages.blank? %> 
      <div class = "alert alert-success">         
        <% @success_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
        
  <div class="block">  
    <div class="data-fluid tabbable">                    
      <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#enabled"><b>Comptes activés</b></a></li>
        <li class=""><a data-toggle="" href="<%= disabled_accounts_list_path %>"><b>Comptes désactivés</b></a></li>
      </ul>
      <div class="tab-content">
        <div id="enabled" class="tab-pane active">
          <%
          @head_color = "green"
          @head_status = "activés"
          @label = "label-success"
          @line_color = "bl_green"
          @name_color = "cgreen"
          @accounts = @enabled_accounts
          @action = "index"
        %>
          <%= render partial: "accounts", :locals => {:head_color => @head_color, :head_status => @head_status, :accounts => @accounts, :label => @label, :line_color => @line_color, :name_color => @name_color, :action => @action} %> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/search.html.erb
<div class="page-header">
    <div class="icon">
        <span class="ico-arrow-right"></span>
    </div>
    <h1>Critères: [<%= params[:terms] %>] <small>Résultats retournés en fonction des critères de recherche</small></h1>
</div>

<div class = "row-fluid">
  <div class = "span12">
    <%= render 'layouts/flash_messages' %>
    <% if !@error_messages.blank? %>  
      <div class = "alert alert-error">         
        <ul>
        <% @error_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% if !@alert_messages.blank? %>  
      <div class = "alert alert-info">         
        <% @alert_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
    <% if !@success_messages.blank? %> 
      <div class = "alert alert-success">         
        <% @success_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>
        
    <div class="block">  
      <%
      @head_color = "purple"
      @head_status = ""
      @label = "label-conflict"
      @line_color = "bl_purple"
      @name_color = "cpurple"
      @action = "search"
    %>
      <%= render partial: "accounts", :locals => {:head_color => @head_color, :head_status => @head_status, :accounts => @accounts, :label => @label, :line_color => @line_color, :name_color => @name_color, :action => @action} %>     
    </div>
  </div>
</div>